### ISSUE TITLE
cmake -B build blinky  error

### ISSUE THREAD

**Issue by flyingcys** [kinsamanka/milkv-zephyros#4]
I have a new problem
```shell
$ cmake -B build blinky 
CMake Error at CMakeLists.txt:13 (find_package):
  Could not find a package configuration file provided by "Zephyr" with any
  of the following names:

    ZephyrConfig.cmake
    zephyr-config.cmake

  Add the installation prefix of "Zephyr" to CMAKE_PREFIX_PATH or set
  "Zephyr_DIR" to a directory containing one of the above files.  If "Zephyr"
  provides a separate development package or SDK, be sure it has been
  installed.
-- Configuring incomplete, errors occurred!
```
What should I do to solve it

**Comment by flyingcys** [comment]
I used export to set the ZEPHYR_BASE environment variable to zephyr in the milkv-zephyros directory, and there were more errors

**Comment by kinsamanka** [comment]
Follow exactly the [Zephyr Getting Started Guide](https://docs.zephyrproject.org/3.6.0/develop/getting_started/index.html) right up to the [Build the Blinky Sample](https://docs.zephyrproject.org/3.6.0/develop/getting_started/index.html#build-the-blinky-sample) part.

Do not forget to perform the `west zephyr-export` part.

**Comment by flyingcys** [comment]
I am new to zephyr and thank you very much for your guidance
