### ISSUE TITLE
no serial log output on uart4

### ISSUE THREAD

**Issue by flyingcys** [kinsamanka/milkv-zephyros#5]
Very happy with your help, I can compile normally and run blink on milkv-duo, but I don't see zephyr serial port running log output on uart4(GP2/GP3). 

Is there any problem with my operation? I'm using the release image [https://github.com/kinsamanka/milkv-zephyros/releases/download/v0.1.1-alpha/milkv-duo_sdcard.img.gz](https://github.com/kinsamanka/milkv-zephyros/releases/download/v0.1.1-alpha/milkv-duo_sdcard.img.gz)

Could you please give me some help?
 Thank you very much!

**Comment by kinsamanka** [comment]
There is output.

The image contains a blinky sample, please try that.

Try using a different uart adaptor, some cannot handle 115200 baud (try lowering the speed [here](https://github.com/kinsamanka/milkv-zephyros/blob/b862b20127ba3a6b1924a251386c98874eecc81d/blinky/milkv_duo.overlay#L22)). Sometimes restarting the secondary processor also works.
